(() => {
  const SUPABASE_URL = "https://iqurvvxmfjfvlkvfsanq.supabase.co";
  const SUPABASE_ANON_KEY = "sb_publishable_0F_NAcjt5hB7cqq8t6y2qA_tFWGv8Oi";
  const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
  const loginUrl = new URL("login.html", window.location.href).href;
  const shopUrl = new URL("shop.html", window.location.href).href;
  const status = (message, type = "info") => { const el = document.getElementById("form-status"); if (el) { el.textContent = message; el.className = `status-message ${type === "error" ? "status-error" : type === "success" ? "status-success" : ""}`.trim(); } };
  const meta = (user) => { const m = user?.user_metadata || {}; const email = user?.email || ""; return { fullName: m.fullName || m.full_name || m.name || email.split("@")[0] || "Marketplace User", role: m.role === "SELLER" ? "SELLER" : "CUSTOMER", phone: m.phone || "", paymentMethod: m.paymentMethod || "CARD", street: m.street || "", city: m.city || "", province: m.province || "", country: m.country || "Zambia", postalCode: m.postalCode || "", storeName: m.storeName || m.fullName || m.full_name || m.name || "" }; };
  const api = async (path, session, body) => { const r = await fetch(`/api${path}`, { method: body ? "POST" : "GET", headers: { "Content-Type": "application/json", Authorization: `Bearer ${session.access_token}` }, ...(body ? { body: JSON.stringify(body) } : {}) }); const p = await r.json().catch(() => ({})); if (!r.ok) throw new Error(p.message || `Request failed (${r.status})`); return p; };
  const sync = async (session, fallback) => { try { return (await api("/auth/me", session)).user; } catch { return (await api("/auth/sync", session, fallback || meta(session.user))).user; } };
  const redirect = (user) => { const ret = new URLSearchParams(location.search).get("returnUrl"); if (ret && /^[\w-]+\.html$/.test(ret)) return location.replace(new URL(ret, location.href).href); location.replace(String(user?.role).toUpperCase() === "SELLER" ? new URL("seller.html", location.href).href : shopUrl); };
  const callback = async () => { const q = new URLSearchParams(location.search); if (q.has("error") || q.has("error_description")) { status(q.get("error_description") || "Authentication failed.", "error"); return true; } if (q.has("code")) { const { error } = await supabaseClient.auth.exchangeCodeForSession(q.get("code")); if (error) { status(error.message, "error"); return true; } history.replaceState({}, document.title, loginUrl); } const { data } = await supabaseClient.auth.getSession(); if (!data.session) return false; const user = await sync(data.session); localStorage.setItem("zmarket-auth", JSON.stringify({ user, tokens: { accessToken: data.session.access_token } })); redirect(user); return true; };
  const bind = (id, handler) => { const old = document.getElementById(id); if (!old) return null; const form = old.cloneNode(true); old.replaceWith(form); form.addEventListener("submit", handler); return form; };
  document.addEventListener("DOMContentLoaded", async () => {
    if (await callback()) return;
    const login = bind("login-form", async (e) => { e.preventDefault(); try { status("Signing you in..."); const { data, error } = await supabaseClient.auth.signInWithPassword({ email: document.getElementById("email").value.trim(), password: document.getElementById("password").value }); if (error) throw error; if (!data.session) throw new Error("Please verify your email before logging in."); const user = await sync(data.session); localStorage.setItem("zmarket-auth", JSON.stringify({ user, tokens: { accessToken: data.session.access_token } })); status("Login successful. Redirecting...", "success"); setTimeout(() => redirect(user), 250); } catch (e) { status(e.message || "Unable to login.", "error"); } });
    if (login) document.getElementById("google-oauth-button")?.addEventListener("click", async () => { try { status("Connecting to Google..."); const { error } = await supabaseClient.auth.signInWithOAuth({ provider: "google", options: { redirectTo: loginUrl } }); if (error) throw error; } catch (e) { status(e.message || "Unable to continue with Google.", "error"); } });
    const register = bind("register-form", async (e) => { e.preventDefault(); const fullName = document.getElementById("full-name").value.trim(), email = document.getElementById("email").value.trim(), password = document.getElementById("password").value, role = document.getElementById("role").value; const m = { fullName, role, phone: document.getElementById("phone")?.value.trim() || "", paymentMethod: document.getElementById("payment-method")?.value || "CARD", street: document.getElementById("street")?.value.trim() || "", city: document.getElementById("city")?.value.trim() || "", province: document.getElementById("province")?.value.trim() || "", country: document.getElementById("country")?.value.trim() || "Zambia", postalCode: document.getElementById("postal-code")?.value.trim() || "", storeName: role === "SELLER" ? fullName : "" }; try { status("Creating your account..."); const { data, error } = await supabaseClient.auth.signUp({ email, password, options: { emailRedirectTo: loginUrl, data: m } }); if (error) throw error; if (!data.session) { status("Account created. Check your email and click the verification link. Then return to Login.", "success"); const b = document.createElement("button"); b.type = "button"; b.className = "button-secondary"; b.textContent = "Resend verification email"; b.style.marginTop = "8px"; b.onclick = async () => { const r = await supabaseClient.auth.resend({ type: "signup", email }); status(r.error ? r.error.message : "Verification email sent again.", r.error ? "error" : "success"); }; register.appendChild(b); return; } const user = await sync(data.session, m); localStorage.setItem("zmarket-auth", JSON.stringify({ user, tokens: { accessToken: data.session.access_token } })); redirect(user); } catch (e) { status(e.message || "Unable to create account.", "error"); } });
    if (register) document.getElementById("google-oauth-button")?.addEventListener("click", async () => { try { status("Connecting to Google..."); const { error } = await supabaseClient.auth.signInWithOAuth({ provider: "google", options: { redirectTo: loginUrl } }); if (error) throw error; } catch (e) { status(e.message || "Unable to continue with Google.", "error"); } });
  });
})();
